---
linters:
  ColorKeyword:
    enabled: true
  Comment:
    enabled: true
  Compass::*:
    enabled: false
  DeclarationOrder:
    enabled: true
  DuplicateProperty:
    enabled: true
  ElsePlacement:
    enabled: true
  EmptyLineBetweenBlocks:
    enabled: true
  EmptyRule:
    enabled: false
  HexLength:
    enabled: true
    style: long
  HexNotation:
    enabled: true
    style: lowercase
  HexValidation:
    enabled: true
  IdWithExtraneousSelector:
    enabled: true
  Indentation:
    enabled: true
    character: space
    width: 2
  LeadingZero:
    enabled: false
  MergeableSelector:
    enabled: true
  PropertySortOrder:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: true
    style: at_least_one_space
  SpaceBeforeBrace:
    enabled: true
  StringQuotes:
    enabled: true
